name:                day2
version:             0.1.0.0
github:              "edgarogh/aoc2023"
license:             MIT
author:              "Edgar Onghena"
maintainer:          "dev@edgar.bzh"

extra-source-files:
- README.md

description:
  Day 2 of the Advent of Code

dependencies:
- base >= 4.7 && < 5
- parsec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  day2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day2

tests:
  day2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day2
